### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by Patrick-56Bit** [cfn-modules/lambda-function#21]
Kindly note the lambda-function module has a couple of missing permissions in the role as follows. These can be added using ManagedPolicyArns but would be great if they are added automatically as is already being done with other modules.

If the DeadLetterQueueModule is set, the following permission should be added:

```
- !If 
            - HasDeadLetterQueueModule
            - Effect: Allow
              Action:
              - 'sqs:SendMessage'
              Resource: {'Fn::ImportValue': !Sub '${DeadLetterQueueModule}-Arn'}
            - !Ref 'AWS::NoValue'
```

If the TracingConfigMode parameter is set to Active the following permission should be added:

```
          - !If 
            - HasActiveTracing
            - Effect: Allow
              Action:
              - 'xray:PutTraceSegments'
              Resource: '*'
            - !Ref 'AWS::NoValue'
```

Thank you.
