### ISSUE TITLE
Ensure that the correct permissions are available to join a VPC

### ISSUE THREAD

**Issue by ptmclean** [cfn-modules/lambda-function#8]
Hi,

I could be wrong, I think there is a missing set of permissions on the policy of the execution role when adding to a VPC. Basically I *think* this needs to be added to the `cfn-modules` policy...
```
          - !If
            - HasVpcModule
            - Effect: Allow
              Action:
              - 'ec2:CreateNetworkInterface'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DeleteNetworkInterface'
              Resource: '*'
            - !Ref 'AWS::NoValue'
```

If this is the case I am happy to PR to fix if it would be helpful.
